name: Coverage Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    # Every day at 2am
    - cron: '0 2 * * *'

jobs:
  android-test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'
          cache: gradle

      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew combinedJacocoTestReport
      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report.csv
          path: app/build/reports/jacoco/test/combinedJacocoTestReport.csv

  report-badge:
    name: JaCoCo Badge Generator
    needs: [ android-test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out the repo
        uses: actions/checkout@v2
      - name: Download the file
        uses: actions/download-artifact@v2
        with:
          name: jacoco-report.csv
          path: app/build/reports/jacoco/test/combinedJacocoTestReport.csv
      - name: Generate JaCoCo Badge
        id: jacoco-badge
        uses: cicirello/jacoco-badge-generator@v2.6.1
        with:
          coverage-label: "Total Coverage"
          jacoco-csv-file: app/build/reports/jacoco/test/combinedJacocoTestReport.csv

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco-badge.outputs.coverage }}"

      - name: Commit and push the badge (if it changed)
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Autogenerated JaCoCo coverage badge'
          add: '*.svg'
