name: Coverage Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    # Every day at 2am
    - cron: '0 2 * * *'

jobs:
  android-test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'
          cache: gradle

      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew combinedJacocoTestReport
      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report.csv
          path: reports/jacoco/test/combinedJacocoTestReport.csv

  generate-report-badge:
    name: JaCoCo Badge Generator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and Downlaod file
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: jacoco-report.csv
      - name: Generate JaCoCo Badge
        id: jacoco-badge
        uses: cicirello/jacoco-badge-generator@v2.6.1
        with:
          coverage-label: "Total Coverage"
          jacoco-csv-file: jacoco-report.csv
    #          generate-branches-badge: true

        - name: Log coverage percentage
          run: |
            echo "coverage = ${{ steps.jacoco-badge.outputs.coverage }}"
    #          echo "branches = ${{ steps.jacoco-badge.outputs.branches }}"

        - name: Commit and push the badge (if it changed)
          uses: EndBug/add-and-commit@v7
          with:
            default_author: github_actions
            message: 'Autogenerated JaCoCo coverage badge'
            add: '*.svg'