name: Release Action
on:
  push:
    branches: [ master ]

jobs:
  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release
        run: |
         VERSION_NAME=$(grep "versionName" app/build.gradle | awk '{print $2}' | tr -d "\"'")
         gh release create $VERSION_NAME --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        
