name: Coverage Tests

on:
  pull_request:
    branches:
      - master
  schedule:
    # Every day at 2am
    - cron: '0 2 * * *'

jobs:
  android-test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'
          cache: gradle

      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew combinedJacocoTestReport

      - name: Generate JaCoCo Badge
        id: jacoco-badge
        uses: cicirello/jacoco-badge-generator@v2.5.0
        with:
          coverage-label: "Total Coverage"
          jacoco-csv-file: reports/jacoco/test/combinedJacocoTestReport.csv
      #          generate-branches-badge: true

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco-badge.outputs.coverage }}"
      #          echo "branches = ${{ steps.jacoco-badge.outputs.branches }}"

      - name: Commit and push the badge (if it changed)
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Autogenerated JaCoCo coverage badge'
          add: '*.svg'